---
driver:
  name: docker

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  # always_update_cookbooks: true

verifier:
  name: inspec

platforms:
        - name: centos-7
          driver_config:
                  forward:
                          - 22:8022
                          - 80:8080

suites:
  - name: default
    run_list:
      - recipe[awesome_customers_rhel::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
